package dao;

// Generated Apr 22, 2014 10:12:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name = "Groupe", catalog = "GED_DB")
public class Groupe implements java.io.Serializable {

	private long idGroupe;
	private String nameGroupe;
	private Set documents = new HashSet(0);

	public Groupe() {
	}

	public Groupe(long idGroupe) {
		this.idGroupe = idGroupe;
	}

	public Groupe(long idGroupe, String nameGroupe, Set documents) {
		this.idGroupe = idGroupe;
		this.nameGroupe = nameGroupe;
		this.documents = documents;
	}

	@Id
	@Column(name = "idGroupe", unique = true, nullable = false)
	public long getIdGroupe() {
		return this.idGroupe;
	}

	public void setIdGroupe(long idGroupe) {
		this.idGroupe = idGroupe;
	}

	@Column(name = "nameGroupe", length = 254)
	public String getNameGroupe() {
		return this.nameGroupe;
	}

	public void setNameGroupe(String nameGroupe) {
		this.nameGroupe = nameGroupe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupe")
	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

}
