package dao;

// Generated Apr 22, 2014 10:12:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "GED_DB")
public class User implements java.io.Serializable {

	private long userId;
	private String userName;
	private Long emailUser;
	private Date birthdayUser;
	private String cniUser;
	private String nationUser;
	private String profitionUser;
	private String pwdUser;
	private Set adminstrators = new HashSet(0);

	public User() {
	}

	public User(long userId) {
		this.userId = userId;
	}

	public User(long userId, String userName, Long emailUser,
			Date birthdayUser, String cniUser, String nationUser,
			String profitionUser, String pwdUser, Set adminstrators) {
		this.userId = userId;
		this.userName = userName;
		this.emailUser = emailUser;
		this.birthdayUser = birthdayUser;
		this.cniUser = cniUser;
		this.nationUser = nationUser;
		this.profitionUser = profitionUser;
		this.pwdUser = pwdUser;
		this.adminstrators = adminstrators;
	}

	@Id
	@Column(name = "userID", unique = true, nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "userName", length = 254)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "emailUser")
	public Long getEmailUser() {
		return this.emailUser;
	}

	public void setEmailUser(Long emailUser) {
		this.emailUser = emailUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birthdayUser", length = 0)
	public Date getBirthdayUser() {
		return this.birthdayUser;
	}

	public void setBirthdayUser(Date birthdayUser) {
		this.birthdayUser = birthdayUser;
	}

	@Column(name = "cniUser", length = 254)
	public String getCniUser() {
		return this.cniUser;
	}

	public void setCniUser(String cniUser) {
		this.cniUser = cniUser;
	}

	@Column(name = "nationUser", length = 254)
	public String getNationUser() {
		return this.nationUser;
	}

	public void setNationUser(String nationUser) {
		this.nationUser = nationUser;
	}

	@Column(name = "profitionUser", length = 254)
	public String getProfitionUser() {
		return this.profitionUser;
	}

	public void setProfitionUser(String profitionUser) {
		this.profitionUser = profitionUser;
	}

	@Column(name = "pwdUser", length = 254)
	public String getPwdUser() {
		return this.pwdUser;
	}

	public void setPwdUser(String pwdUser) {
		this.pwdUser = pwdUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getAdminstrators() {
		return this.adminstrators;
	}

	public void setAdminstrators(Set adminstrators) {
		this.adminstrators = adminstrators;
	}

}
