package dao;

// Generated Apr 22, 2014 10:12:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WritedBy generated by hbm2java
 */
@Entity
@Table(name = "writedBy", catalog = "GED_DB")
public class WritedBy implements java.io.Serializable {

	private WritedById id;
	private Document document;

	public WritedBy() {
	}

	public WritedBy(WritedById id, Document document) {
		this.id = id;
		this.document = document;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "userID", nullable = false)),
			@AttributeOverride(name = "idDocument", column = @Column(name = "idDocument", nullable = false)) })
	public WritedById getId() {
		return this.id;
	}

	public void setId(WritedById id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDocument", nullable = false, insertable = false, updatable = false)
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

}
