package dao;

// Generated Apr 22, 2014 10:12:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WritedById generated by hbm2java
 */
@Embeddable
public class WritedById implements java.io.Serializable {

	private long userId;
	private long idDocument;

	public WritedById() {
	}

	public WritedById(long userId, long idDocument) {
		this.userId = userId;
		this.idDocument = idDocument;
	}

	@Column(name = "userID", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "idDocument", nullable = false)
	public long getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(long idDocument) {
		this.idDocument = idDocument;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WritedById))
			return false;
		WritedById castOther = (WritedById) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getIdDocument() == castOther.getIdDocument());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getIdDocument();
		return result;
	}

}
