package beans;

// Generated Apr 23, 2014 6:50:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdminstratorId generated by hbm2java
 */
@Embeddable
public class AdminstratorId implements java.io.Serializable {

	private long userId;
	private long idAdmin;

	public AdminstratorId() {
	}

	public AdminstratorId(long userId, long idAdmin) {
		this.userId = userId;
		this.idAdmin = idAdmin;
	}

	@Column(name = "userID", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "idAdmin", nullable = false)
	public long getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(long idAdmin) {
		this.idAdmin = idAdmin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdminstratorId))
			return false;
		AdminstratorId castOther = (AdminstratorId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getIdAdmin() == castOther.getIdAdmin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getIdAdmin();
		return result;
	}

}
