package beans;

// Generated Apr 23, 2014 6:50:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Adminstrator generated by hbm2java
 */
@Entity
@Table(name = "Adminstrator", catalog = "GED_DB")
public class Adminstrator implements java.io.Serializable {

	private AdminstratorId id;
	private User user;
	private String loginAdmin;
	private String pwdAdmin;

	public Adminstrator() {
	}

	public Adminstrator(AdminstratorId id, User user) {
		this.id = id;
		this.user = user;
	}

	public Adminstrator(AdminstratorId id, User user, String loginAdmin,
			String pwdAdmin) {
		this.id = id;
		this.user = user;
		this.loginAdmin = loginAdmin;
		this.pwdAdmin = pwdAdmin;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "userID", nullable = false)),
			@AttributeOverride(name = "idAdmin", column = @Column(name = "idAdmin", nullable = false)) })
	public AdminstratorId getId() {
		return this.id;
	}

	public void setId(AdminstratorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "loginAdmin", length = 254)
	public String getLoginAdmin() {
		return this.loginAdmin;
	}

	public void setLoginAdmin(String loginAdmin) {
		this.loginAdmin = loginAdmin;
	}

	@Column(name = "pwdAdmin", length = 254)
	public String getPwdAdmin() {
		return this.pwdAdmin;
	}

	public void setPwdAdmin(String pwdAdmin) {
		this.pwdAdmin = pwdAdmin;
	}

}
