package beans;

// Generated Apr 23, 2014 6:50:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name = "History", catalog = "GED_DB")
public class History implements java.io.Serializable {

	private long idHistory;
	private Date dateHistory;
	private String nameUser;
	private String loginUser;
	private Set documents = new HashSet(0);

	public History() {
	}

	public History(long idHistory) {
		this.idHistory = idHistory;
	}

	public History(long idHistory, Date dateHistory, String nameUser,
			String loginUser, Set documents) {
		this.idHistory = idHistory;
		this.dateHistory = dateHistory;
		this.nameUser = nameUser;
		this.loginUser = loginUser;
		this.documents = documents;
	}

	@Id
	@Column(name = "idHistory", unique = true, nullable = false)
	public long getIdHistory() {
		return this.idHistory;
	}

	public void setIdHistory(long idHistory) {
		this.idHistory = idHistory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateHistory", length = 0)
	public Date getDateHistory() {
		return this.dateHistory;
	}

	public void setDateHistory(Date dateHistory) {
		this.dateHistory = dateHistory;
	}

	@Column(name = "nameUser", length = 254)
	public String getNameUser() {
		return this.nameUser;
	}

	public void setNameUser(String nameUser) {
		this.nameUser = nameUser;
	}

	@Column(name = "loginUser", length = 254)
	public String getLoginUser() {
		return this.loginUser;
	}

	public void setLoginUser(String loginUser) {
		this.loginUser = loginUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "history")
	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

}
