package beans;

// Generated Apr 23, 2014 6:50:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Repertory generated by hbm2java
 */
@Entity
@Table(name = "Repertory", catalog = "GED_DB")
public class Repertory implements java.io.Serializable {

	private long idRepertory;
	private String nameRepertory;
	private Date dateCreation;
	private Date dateUpdate;
	private Set documents = new HashSet(0);
	private Set sousRepertories = new HashSet(0);

	public Repertory() {
	}

	public Repertory(long idRepertory) {
		this.idRepertory = idRepertory;
	}

	public Repertory(long idRepertory, String nameRepertory, Date dateCreation,
			Date dateUpdate, Set documents, Set sousRepertories) {
		this.idRepertory = idRepertory;
		this.nameRepertory = nameRepertory;
		this.dateCreation = dateCreation;
		this.dateUpdate = dateUpdate;
		this.documents = documents;
		this.sousRepertories = sousRepertories;
	}

	@Id
	@Column(name = "idRepertory", unique = true, nullable = false)
	public long getIdRepertory() {
		return this.idRepertory;
	}

	public void setIdRepertory(long idRepertory) {
		this.idRepertory = idRepertory;
	}

	@Column(name = "nameRepertory", length = 254)
	public String getNameRepertory() {
		return this.nameRepertory;
	}

	public void setNameRepertory(String nameRepertory) {
		this.nameRepertory = nameRepertory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCreation", length = 0)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateUpdate", length = 0)
	public Date getDateUpdate() {
		return this.dateUpdate;
	}

	public void setDateUpdate(Date dateUpdate) {
		this.dateUpdate = dateUpdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "repertory")
	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "repertory")
	public Set getSousRepertories() {
		return this.sousRepertories;
	}

	public void setSousRepertories(Set sousRepertories) {
		this.sousRepertories = sousRepertories;
	}

}
