package beans;

// Generated Apr 23, 2014 6:50:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TypeDocumentId generated by hbm2java
 */
@Embeddable
public class TypeDocumentId implements java.io.Serializable {

	private long idDocument;
	private int idTypeDoc;

	public TypeDocumentId() {
	}

	public TypeDocumentId(long idDocument, int idTypeDoc) {
		this.idDocument = idDocument;
		this.idTypeDoc = idTypeDoc;
	}

	@Column(name = "idDocument", nullable = false)
	public long getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(long idDocument) {
		this.idDocument = idDocument;
	}

	@Column(name = "idTypeDoc", nullable = false)
	public int getIdTypeDoc() {
		return this.idTypeDoc;
	}

	public void setIdTypeDoc(int idTypeDoc) {
		this.idTypeDoc = idTypeDoc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TypeDocumentId))
			return false;
		TypeDocumentId castOther = (TypeDocumentId) other;

		return (this.getIdDocument() == castOther.getIdDocument())
				&& (this.getIdTypeDoc() == castOther.getIdTypeDoc());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdDocument();
		result = 37 * result + this.getIdTypeDoc();
		return result;
	}

}
