package beans;

// Generated Apr 23, 2014 6:50:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TypeDocument generated by hbm2java
 */
@Entity
@Table(name = "TypeDocument", catalog = "GED_DB")
public class TypeDocument implements java.io.Serializable {

	private TypeDocumentId id;
	private Document document;
	private String nameTypeDoc;

	public TypeDocument() {
	}

	public TypeDocument(TypeDocumentId id, Document document) {
		this.id = id;
		this.document = document;
	}

	public TypeDocument(TypeDocumentId id, Document document, String nameTypeDoc) {
		this.id = id;
		this.document = document;
		this.nameTypeDoc = nameTypeDoc;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDocument", column = @Column(name = "idDocument", nullable = false)),
			@AttributeOverride(name = "idTypeDoc", column = @Column(name = "idTypeDoc", nullable = false)) })
	public TypeDocumentId getId() {
		return this.id;
	}

	public void setId(TypeDocumentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDocument", nullable = false, insertable = false, updatable = false)
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	@Column(name = "nameTypeDoc", length = 254)
	public String getNameTypeDoc() {
		return this.nameTypeDoc;
	}

	public void setNameTypeDoc(String nameTypeDoc) {
		this.nameTypeDoc = nameTypeDoc;
	}

}
